<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account details' => '',
    'Actions' => '',
    'Activate' => '',
    'Active' => '',
    'Are you sure you want to activate this user?' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Assignments' => '',
    'Block' => '',
    'Blocked' => '',
    'Change password' => '',
    'Create' => '',
    'Create User' => '',
    'Created At' => '',
    'Current password' => '',
    'Delete' => '',
    'Delete User' => '',
    'Email' => '',
    'Incorrect current password.' => '',
    'Incorrect username or password.' => '',
    'Information' => '',
    'Login' => '',
    'New Password' => '',
    'New Password repeat' => '',
    'Password' => '',
    'Password Repeat' => '',
    'Password has benn changed.' => '',
    'Pending' => '',
    'Permissions' => '',
    'Register' => '',
    'Registration IP' => '',
    'Remember me' => '',
    'Roles' => '',
    'Status' => '',
    'Submit' => '',
    'The email has been already used' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Unblock' => '',
    'Update User' => '',
    'Updated At' => '',
    'User' => '',
    'User can not activate.' => '',
    'User can not delete.' => '',
    'User has been Activated.' => '',
    'User has been created' => '',
    'User has been deleted.' => '',
    'User has been updated' => '',
    'Username' => '',
    'Users' => '',
    'You can not activate own account.' => '',
    'You can not block own account.' => '',
    'You can not delete own account.' => '',
    'Your account has been created.' => '',
];
