<?php

namespace atans\user\controllers;

use atans\user\models\UserSearch;
use Yii;
use yii\web\Controller;

class AdminController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = Yii::createObject(UserSearch::className());
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionCreate()
    {

    }

    public function actionUpdate($id)
    {

    }

    public function actionView($id)
    {

    }

}